### ISSUE TITLE
unable to dump ISA with cliloader

### ISSUE THREAD

**Issue by guoyejun** [intel/opencl-intercept-layer#175]
hi,

i tried with https://github.com/intel/opencl-intercept-layer/blob/master/docs/cliloader.md, but met issues. Could please help, thanks.  My system is ubuntu 18.04.

Here is my steps
```
$ git clone https://github.com/intel/opencl-intercept-layer.git
$ cd opencl-intercept-layer/

$ mkdir build
$ cd build
$ cmake -DENABLE_CLILOADER=1 ..
$ make

// then try to dump
$ export DumpKernelISABinaries=1
$ ./cliloader/cliloader clinfo
// only an empty file is generated
$ ls ~/CLIntercept_Dump/clinfo/clintercept_report.txt -s
0 /home/yguo18/CLIntercept_Dump/clinfo/clintercept_report.txt

// i tried with other program, still no ISA dumped.
// i'm sure that OpenCL kernels are executed in this program.
$ /work/gfx/opencl-intercept-layer/build/cliloader/cliloader ./ffmpeg ...
$ cat ~/CLIntercept_Dump/ffmpeg/clintercept_report.txt 
Total Enqueues: 72
```

thanks

**Comment by bashbaug** [comment]
Hello!

A couple of things to try (I'm assuming you are running with an Intel GPU):

1. When you set controls for the intercept layer they need to be prefixed with `CLI_` ([link](https://github.com/intel/opencl-intercept-layer/blob/master/docs/controls.md#environment-variables)), so you should use:

```sh
$ export DumpKernelISABinaries=1
```

2. Alternatively, for dumping kernel ISA binaries, you can pass the `--dump-kernel-isa-binaries` option to `cliloader`, so:

```sh
$ cliloader --dump-kernel-isa-binaries clinfo
```

Both of these methods worked for me on my test system:

```sh
$ ls ~/CLIntercept_Dump/clinfo/
CLI_0000_0585D671_0000_00000000_GPU_sum.isabin  clintercept_report.txt
```

Note that the empty report file is not a surprise from `clinfo` since it doesn't enqueue any OpenCL commands.

**Comment by guoyejun** [comment]
thanks, i tried with --dump-kernel-isa-binaries and it works.
