### ISSUE TITLE
Local install for Linux

### ISSUE THREAD

**Issue by zjin-lcf** [intel/opencl-intercept-layer#183]
Could you please add a section about how a user can install the tool without root access to the real ICD ?

Thanks

**Comment by bashbaug** [comment]
Thanks for reaching out!  I will look into enhancing the installation instructions.

In the short term, here are two suggestions:

1. My recommended solution is to build and install the intercept layer and [cliloader](https://github.com/intel/opencl-intercept-layer/blob/master/docs/cliloader.md) into a directory where you have access, then to use it to selectively intercept your application.  For example, I'll usually install into my home directory, and then I'll either add `$HOME/bin` to my path, or I'll just execute with `~/bin/cliloader ...`.

2. Alternatively, the [targeted usage](https://github.com/intel/opencl-intercept-layer/blob/master/docs/install.md#targeted-usage) method can be used without root access and provides a similar experience as the "local install".  Ultimately this uses the same fundamental mechanisms as `cliloader`, except you are responsible for setting up the right environment variables instead of `cliloader`.

Give these a try and let me know if they work - thanks!

**Comment by bashbaug** [comment]
I've tried to improve these instructions, see https://github.com/intel/opencl-intercept-layer/pull/185.

Feel free to re-open this issue (or create a new one) if you have additional suggestions for improvement.  Thanks!
