### ISSUE TITLE
[windows] app exits immediately and no logs are produced

### ISSUE THREAD

**Issue by SebastianLuzynski** [intel/opencl-intercept-layer#222]
## Observed Behavior
OpenCL application instantly closes when running in same directory with clintercept OpenCL.dll on Windows. Happens for all opencl apps on windows for me. I have some older versions of clintercept and they work correctly. Issue observed with 3.0.2 release and on master branch.

I've also tested it with very simple `clinfo.exe` app, that simply prints some basic GPU information and it also doesn't work. I've tested both with OpenCL.dll in same working directory and with cliloader.exe

## Desired Behavior
Application should finish as usual and produce logs in C:\Intel\CLintercept

## Steps to Reproduce
Build clintercept from source from release 3.0.2
copy OpenCL.dll to application working directory
Invoke app from command line
Application exits immediately, no logs are created

Uploading intercept built by me. This is built from release 3.0.2
[clintercept.zip](https://github.com/intel/opencl-intercept-layer/files/6953131/clintercept.zip)

Flags used
```
"LogToFile"=dword:00000001
"BuildLogging"=dword:00000001
"CallLogging"=dword:00000001
"ErrorLogging"=dword:00000001
"SimpleDumpProgram"=dword:00000001
"DumpProgramsScript"=dword:00000001
"DumpProgramsInject"=dword:00000001
"InjectPrograms"=dword:00000001
"InjectProgramSource"=dword:00000001
"CallLoggingThreadId"=dword:00000001
"FinishAfterEnqueue"=dword:00000000
"AppendFiles"=dword:00000000
```

**Comment by bashbaug** [comment]
Hi, if you disable `LogToFile` do you see any CLIntercept output (to stderr)?

I wonder if you don't have permission to create or open files in the default log directory.  If this is the case you may also want to try using `DumpDir` to set your directory to a location that you know you have access to ([link](https://github.com/intel/opencl-intercept-layer/blob/master/docs/controls.md#dumpdir-string)).

**Comment by SebastianLuzynski** [comment]
I’ve tried to run very basic `clinfo.exe` app without any env variables set and no output has been produced, application has exited immediately. I’ve also tried with `cliloader.exe clinfo.exe` but effect is the same – no output in stderr or stdout.

**Comment by bashbaug** [comment]
OK, interesting.  High-level, I think one of the following is occurring, and we need to figure out which one:

1. Is there something different about the way you are building the intercept layer?  Which compiler are you using?  Are you passing any special build options?  Are you testing a 32-bit application or a 64-bit application?  Are you building a 32-bit intercept layer or a 64-bit intercept layer?
2. Are you testing a Release or RelWithDebInfo build?  If you are testing a Debug build please run with a debugger attached since the debug build may generate asserts when some controls are enabled.
3. Can you please describe how you are installing the intercept layer?  Do you have any controls set, either via environment variables or registry settings?  Is there anything else in the directory where you are running your application?  Are you using a standard ICD loader in a standard location?

If it's helpful, here is a test on my machine with the latest intercept layer:

Initially the intercept layer is disabled (the DLL has a `_` suffix):

```
D:\GIT\CLIntercept\test>dir
 Volume in drive D is SECOND HD
 Volume Serial Number is BFF0-02F0

 Directory of D:\GIT\CLIntercept\test

08/10/2021  10:32 AM    <DIR>          .
08/10/2021  10:32 AM    <DIR>          ..
12/29/2020  11:29 AM            45,056 enumopencl.exe
08/10/2021  10:31 AM         1,126,400 OpenCL.dll_
               2 File(s)      1,171,456 bytes
               2 Dir(s)  155,956,824,576 bytes free

D:\GIT\CLIntercept\test>enumopencl.exe
Enumerated 1 platforms.

<application output>
```

Renaming the intercept layer DLL "enables" it:

```
D:\GIT\CLIntercept\test>ren OpenCL.dll_ OpenCL.dll
```

Now there is intercept layer output, showing the latest commit (ed71523):

```
D:\GIT\CLIntercept\test>enumopencl.exe
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
CLIntercept (64-bit) is loading...
CLIntercept file location: D:\GIT\CLIntercept\test\OpenCL.dll
CLIntercept URL: https://github.com/intel/opencl-intercept-layer
CLIntercept git description: v3.0.2-15-ged71523
CLIntercept git refspec: refs/heads/master
CLIntercept git hash: ed71523076304c573778ee515485c65e013cf25b
CLIntercept optional features:
    cliloader(supported)
    cliprof(supported)
    kernel overrides(supported)
    ITT tracing(NOT supported)
    MDAPI(supported)
    clock(steady_clock)
CLIntercept environment variable prefix: CLI_
CLIntercept registry key: SOFTWARE\INTEL\IGFX\CLINTERCEPT
Trying to load dispatch from: real_opencl.dll
Couldn't load library: real_opencl.dll
Trying to load dispatch from: C:\WINDOWS/syswow64/opencl.dll
Couldn't load library: C:\WINDOWS/syswow64/opencl.dll
Trying to load dispatch from: C:\WINDOWS/system32/opencl.dll
Couldn't get exported function pointer to: clGetGLContextInfoKHR
... success!
Timer Started!
... loading complete.
Enumerated 1 platforms.

<application output>
CLIntercept is shutting down...
... shutdown complete.
```

**Comment by SebastianLuzynski** [comment]
I think I found the reason why it doesn't work, although it's really weird to me. I compiled my clintercept using ninja - `cmake ../ -G Ninja` and it does not work. I've tried to leave default cmake options and simply compile it via Visual studio - `cmake ../`, open solution and build. CLintercept built with visual studio solution works for me.

**Comment by bashbaug** [comment]
Interesting.

As an experiment I tried building using Ninja and it seemed to work for me.  I used the 64-bit VS 2019 build tools.

```
D:\GIT\CLIntercept\ninja_test>ninja --version
1.8.2

D:\GIT\CLIntercept\ninja_test>cl
Microsoft (R) C/C++ Optimizing Compiler Version 19.26.28806 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.
```

One thing to be aware of is that the command line above will build a Debug config, so it's possible you could have been hitting an assert with your Ninja build? It would be interesting to see if you still get the immediate exit with a Release or RelWithDebInfo config: `cmake -G Ninja .. -DCMAKE_BUILD_TYPE=RelWithDebInfo`, or what happens if you run with a debugger attached.

Regardless, I'm glad things appear to be working now!

**Comment by bashbaug** [comment]
Hi, is any additional follow-up needed for this issue or can it be closed?
