### ISSUE TITLE
Add Hash to Call Logging Kernel Name

### ISSUE THREAD

**Issue by bashbaug** [intel/opencl-intercept-layer#26]
## Observed Behavior

CallLogging frequently includes a decoded kernel name in the log, for example:

````
>>>> clSetKernelArg( GenerateJuliaSet ): kernel = 0717BDA8, ...
````

To differentiate between multiple kernels with the same name, DevicePerformanceTimeHashTracking will append hash information information in the report:

````
                       Function Name,  Calls,     ...
GenerateJuliaSet(0000_3F40E1CD_0001),      4,     ...
````

The hash is not included in the log, though, which makes it difficult to differentiate between calls affecting kernels with the same name.

## Desired Behavior

Include the program hash in the log, when DevicePerformanceTimeHashTracking is enabled.  For example:

````
>>>> clSetKernelArg( GenerateJuliaSet(0000_3F40E1CD_0001) ): kernel = 0717BDA8, ...
````

## Steps to Reproduce

Set CallLogging, DevicePerformanceTiming, and DevicePerformanceTimeHashTracking, and run a program that enqueues a kernel.

**Comment by trbauer** [comment]
It would also be nice to have the hash emitted in `clintercept_log.txt` when the program is built `clBuildProgram`. Maybe that is part of the output when we dump the .cl file and options .txt though?

    >>>> clBuildProgram: program = 0000013A53180C50, pfn_notify = 0000000000000000, EnqueueCounter: 1
    Build Info for program 0000013A53180C50 (0001_HASHHERE_0000), number 0, compile 0, for 1 device(s):
                                            ^^^^^^^^^^^^^^^^^^^^ here for example

This way when we see 

    >>>> clSetKernelArg( GenerateJuliaSet(0000_3F40E1CD_0001) ): kernel = 0717BDA8, ...

we can relate it to the build call.

Note, the hash is already implicitly emitted if we are dumping the source (`DumpProgramSource`).

**Comment by trbauer** [comment]
Just to be clear this proposes to suffix kernel names wherever used. Not just `clSetKernelArg`.

**Comment by bashbaug** [comment]
Was #27 closed by mistake?  I think it has relevance to this issue.

I have some of this working in a branch, but there are a few details to work out:
https://github.com/bashbaug/opencl-intercept-layer/tree/program_options_hash

With these changes...

* I've added a hash of the program options when its relevant, as described in #27.
* The hash string gets emitted as part of BuildLogging:

````
>>>> clBuildProgram: program = 05443988, pfn_notify = 00000000
Build Info for program 05443988 (0000_3F40E1CD_0000_0F7F3CA6) for 1 device(s):
...
````

* The same hash string gets emitted as part of the "kernel name" with CallLogging, when DevicePerformanceTimeHashTracking is also set:

````
>>>> clSetKernelArg( GenerateJuliaSet(0000_3F40E1CD_0000_0F7F3CA6) ): kernel = 07426200, ...
````

* It also gets emitted in the host performance time report.  (It was already included in the device performance time report).

Things we need to decide:

* Is the program options hash useful?  I kind of like it since it makes it more obvious when two kernels are built with the same options, although it's another 8-9 characters to mentally parse.
* If we have the program options hash, do we also need the compile count?  We currently have a control to omit the program number if it's not needed, so we could do the same thing for the compile count, or we could eliminate the compile count completely.
* Do we really want the hash string everywhere?  Debatably it's not very useful for host performance timing, for example.
* It still doesn't feel entirely right to me to change how the logging is displayed based on the DevicePerformanceTimingHashTracking control.  Perhaps a different control should be added for logging instead? Or should these controls be refactored completely?

I have a bit more work to do on the implementation itself, but wanted to give an update and opportunity for feedback.

**Comment by trbauer** [comment]
My position on the opens.

1. Yes the build options hash is helpful. We could share the hash with the program (bits or source). That is in build program. prg_hash = hash(opts,hash(bits or source,0)).

2. I would favor seeing the compile count go away but don't feel that strongly.
In general I wouldn't bind any hash to a program until the final step. That is, don't even present the program hash until we get to the final step that added the options.  As the program is mutated (clCompileProgram/clBuildProgram adds options etc..,) update the hash as needed based on the new input. 

The program create index isn't strictly necessary except that it makes hash collisions absolutely impossible and gives the reader a little extra sanity. One option is to make the counters two character wide instead of the usual 4, and maybe even use hex if you want more efficiency. The fields will widen to three chars or more if needed (and we clearly use separators between the parts).

Keeping the hashes for build options and build source separate is nice, but I don't feel that strongly either way.

3. Fair point. I was thinking there would be a single control one way or the other. For instance if one only wants host timing, then why bother at all with distinguishing which kernel. Let's just emit.

    clSetKernelArg: kernel = ....

Then if the user enables kernel names or something (`KernelHashNames`?), we go the extra step.

    clSetKernelArg( foo(0001_...) ): kernel = ....

A corollary is that if `KernelHashNames` is off, program build APIs (clBuildProgram, clCompileProgram) don't need to present the hash in the API stream.

4. I don't quite understand this point. My immediate instinct is to favor consistency even at the cost of refactors or breaking changes, especially early on in a project's public life.

**Comment by trbauer** [comment]
Another note, linkers liberally use `$` as a delimiter for the hidden parts of kernels. We could write.

Instead of:

    Function Name,  Calls,     ...
    GenerateJuliaSet(0000_3F40E1CD_0001),      4,     ...

We could have.

    Function Name,  Calls,     ...
    GenerateJuliaSet$0000_3F40E1CD_0001,      4,     ...

This saves you character and in the API trace you don't get nested parentheses.

   clSetKernelArg( GenerateJuliaSet( 0000_3F40E1CD_0001 ) ): kernel = ..., ... other API args

Also FWIW. The API refactoring task I am working on would move the decoding hint to the kernel part.

Something like:

    clSetKernelArg: kernel = 0x7FEE1320 [ GenerateJuliaSet( 0000_3F40E1CD_0001 ) ], ... other API args

Or with the `$` separator that would be 

    clSetKernelArg: kernel = 0x7FEE1320 [ GenerateJuliaSet$0000_3F40E1CD_0001 ], ... other API args

This allows us to uniformly decode objects that we care about per API parameter rather than making certain API calls specially work to decode kernel.

**Comment by bashbaug** [comment]
>> It still doesn't feel entirely right to me to change how the logging is displayed based on the DevicePerformanceTimingHashTracking control. Perhaps a different control should be added for logging instead? Or should these controls be refactored completely?

> I don't quite understand this point. My immediate instinct is to favor consistency even at the cost of refactors or breaking changes, especially early on in a project's public life.

I think this is what I'm getting at: I'd prefer to deprecate DevicePerformanceTimeHashTracking and replace it with another control that appends the hash to the kernel name "everywhere" (for some definition of everywhere).  This way it's clear that the control is affecting more than just the device performance time report, and there aren't redundant controls.

I'll play around with this and with the `$` separator.  Thanks!

**Comment by bashbaug** [comment]
The changes added by PR #47 are intended to address this issue.  Can you please check and see if anything more is needed or if this issue may be closed?  Thanks!

**Comment by bashbaug** [comment]
I think this is fixed.  If it's not, feel free to re-open this issue or add a new one.  Thanks!
