### ISSUE TITLE
Cannot get cliloader result for python app with virtualenv on Windows

### ISSUE THREAD

**Issue by yeonbok** [intel/opencl-intercept-layer#327]
## Observed Behavior
- (my_env) cliloader.exe python [app_name.py]  => No cliloader log (Total Enqueues: 0)
- (my_env) cliloader.exe /actual/path/to/python [app_name.py] => cliloader log is obtained as expected  

## Desired Behavior
- Even with python virtualenv, it is expected to provide clilog 

(Describe the behavior that you would like to see instead.)

## Steps to Reproduce
- C:\Users\xxxx\AppData\Local\Programs\Python\Python310\python.exe -m venv my_env
- run my_env\Script\Activate
- run python app 

(my_env) HOME_NAME> cliloader.exe python run_app.py -d GPU
                                                -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
                                                CLIntercept (64-bit) is loading...
                                                CLIntercept file location: ..\opencl.dll
                                                CLIntercept URL: https://github.com/intel/opencl-intercept-layer
                                                CLIntercept git description: v3.0.3-56-g10a578e
                                                CLIntercept git refspec: refs/heads/main
                                                CLIntercept git hash: 10a578ed3217e232db4d9276a949362b7f2e29d9
                                                CLIntercept optional features:
    cliloader(supported)
    cliprof(supported)
    kernel overrides(supported)
    ITT tracing(NOT supported)
    MDAPI(supported)
    Demangling(NOT supported)
    clock(steady_clock)
                                                CLIntercept environment variable prefix: CLI_
                                                CLIntercept registry key: SOFTWARE\INTEL\IGFX\CLINTERCEPT
                                                Trying to load dispatch from: real_opencl.dll
                                                Couldn't load library: real_opencl.dll
                                                Trying to load dispatch from: C:\windows/syswow64/opencl.dll
                                                Couldn't load library: C:\windows/syswow64/opencl.dll
                                                Trying to load dispatch from: C:\windows/system32/opencl.dll
                                                Couldn't get exported function pointer to: clGetGLContextInfoKHR
                                                ... success!
                                                Control AppendFiles is set to non-default value: true
                                                Control LogIndent is set to non-default value: 48
                                                Control CallLogging is set to non-default value: true
                                                Control CallLoggingEnqueueCounter is set to non-default value: true
                                                Control CallLoggingThreadId is set to non-default value: true
                                                Control CallLoggingThreadNumber is set to non-default value: true
                                                Control ChromeCallLogging is set to non-default value: true
                                                Control EventCallbackLogging is set to non-default value: true
                                                Control QueueInfoLogging is set to non-default value: true
                                                Control EventChecking is set to non-default value: true
                                                Control LeakChecking is set to non-default value: true
                                                Control USMChecking is set to non-default value: true
                                                Control DumpDir is set to non-default value: D:/mylog/DumpCLI
                                                Control ReportToStderr is set to non-default value: true
                                                Control HostPerformanceTiming is set to non-default value: true
                                                Control HostPerformanceTimeLogging is set to non-default value: true
                                                Control DevicePerformanceTimeLogging is set to non-default value: true
                                                Control DevicePerformanceTimelineLogging is set to non-default value: true
                                                Control ChromePerformanceTiming is set to non-default value: true
                                                Control ChromePerformanceTimingInStages is set to non-default value: true
                                                Control ChromePerformanceTimingPerKernel is set to non-default value: true
                                                Timer Started!
                                                ... loading complete.
Total Enqueues: 0
 
 
Leak Checking:
 

(Describe how to reproduce the issue.  Some information you may want to include:

* Any Intercept Layer for OpenCL Applications controls you are setting.
* The application you ran.  For large or proprietary applications, it will likely be easier to address your issue if you include a simpler reproducer.
* The OpenCL implementation and device you tested on.
* Your operating system, and any other relevant system information.

Some of this information may automatically be included if you attach your Intercept Layer for OpenCL Applications log, particularly if you set [CLInfoLogging](https://github.com/intel/opencl-intercept-layer/blob/main/docs/controls.md#clinfologging-bool).)

**Comment by bashbaug** [comment]
I think I know what is happening here now, but I'm not entirely sure how to fix it.

As background, the way the cliloader utility works on Windows is a bit complicated, but it basically tries to mimic similar behavior to the Linux LD_PRELOAD environment variable:

1. First, cliloader loads the OpenCL Intercept Layer DLL and gets a pointer to the Windows-specific initialization function.
2. Next, cliloader creates the requested process (from the command line) in a suspended state.
3. Then cliloader creates a thread in the target process to load the OpenCL Intercept Layer DLL in the target process.
4. Once the OpenCL Intercept Layer DLL is open in the target process, cliloader creates another thread to call the Windows-specific initialization function in the target process.  This isn't always strictly necessary, but it is in some cases if the target process loads the "real" OpenCL ICD loader DLL when it is created then we need to change the function pointers in the target process to the OpenCL Intercept Layer function pointers instead.
5. Finally, cliloader tells the target process to resume, now that the OpenCL Intercept Layer DLL is installed and initialized in it.

Unfortunately, what seems to be happening in the virtualenv case is that the target process (the python.exe in the Scripts folder) is a sort of loader process itself that spawns another process for the "real" python executable.  Because cliloader has no notion of this additional process it doesn't have the OpenCL Intercept Layer DLL loaded into it and no OpenCL commands are intercepted, leading to the reported behavior.

Here is a good link with more information:
https://stackoverflow.com/questions/76637592/virtual-environment-python-exe-calling-global-python-exe

I definitely see the two python.exe processes on my system also:
![image](https://github.com/intel/opencl-intercept-layer/assets/14812095/e26140fa-9d33-42f2-bcdc-a50f90bd5312)

When requesting to execute the "real" python executable directly the OpenCL Intercept Layer DLL gets loaded into the correct process and this is why everything "works".  This also explains why a "local install" to the Scripts folder doesn't work.

I'll do a bit more research to see if there's something more the OpenCL Intercept Layer can do to "fix" this, but if not, the best we may be able to do is good documentation in the "FAQ and Troubleshooting" [doc](https://github.com/intel/opencl-intercept-layer/blob/main/docs/FAQ.md).

**Comment by bashbaug** [comment]
I've updated the FAQ with a description of the problem and possible workarounds in #329.  Please take a look - thanks!
