### ISSUE TITLE
[Windows] [DLL load error] cliloader Error: loading DLL: The specified module could not be found

### ISSUE THREAD

**Issue by xiang1guo** [intel/opencl-intercept-layer#370]
Hi, team

When I am trying to use cliloader on windows, I met an error:
`cliloader Error: loading DLL: The specified module could not be found.`

The build option I used:
`cmake -G "Visual Studio 17 2022" -DCMAKE_BUILD_TYPE=Release -DENABLE_CLILOADER=TRUE ..`

The cml I used:
`cliloader.exe my_application.exe args ...`

Can you help on this issue? Not sure if I missed something. Thanks!

**Comment by bashbaug** [comment]
Hello, you can usually get more information about cliloader errors by adding `--debug` to your list of cliloader command line options.  In this case though, I'm fairly sure that this error message...

`cliloader Error: loading DLL: The specified module could not be found.`

... means that cliloader was unable to find the OpenCL Intercept Layer DLL.  On Windows, cliloader expects to find the DLL in the same directory as the cliloader executable.  If you build the "install" target then the executable and the DLL will be copied to the same install folder, otherwise you will need to copy it yourself.

Can you try with the OpenCL Intercept Layer DLL in the same directory as cliloader?

If this still does not work, can you please include the output with the `--debug` command line option?  It will look something like this:

```
>\git\CLIntercept\Builds\x64\RelWithDebInfo\cliloader.exe --debug julia.exe
[cliloader debug] setting environment variable CLI_ReportToStderr to 1
[cliloader debug] position after parsing arg '\git\CLIntercept\Builds\x64\RelWithDebInfo\cliloader.exe' is 56
[cliloader debug] position after parsing arg '--debug' is 65
[cliloader debug] position after skipping non-whitespace characters is 65
[cliloader debug] position after skipping whitespace characters is 66
[cliloader debug] pProcessName is non-NULL: \cliloader.exe
[cliloader debug] process directory is: D:\git\CLIntercept\Builds\x64\RelWithDebInfo
[cliloader debug] CLI_SuppressLogging is currently:
[cliloader debug] path to OpenCL.dll is: D:\git\CLIntercept\Builds\x64\RelWithDebInfo\opencl.dll
[cliloader debug] loaded DLL
```

Thanks!

**Comment by xiang1guo** [comment]
> Hello, you can usually get more information about cliloader errors by adding `--debug` to your list of cliloader command line options. In this case though, I'm fairly sure that this error message...
> 
> `cliloader Error: loading DLL: The specified module could not be found.`
> 
> ... means that cliloader was unable to find the OpenCL Intercept Layer DLL. On Windows, cliloader expects to find the DLL in the same directory as the cliloader executable. If you build the "install" target then the executable and the DLL will be copied to the same install folder, otherwise you will need to copy it yourself.
> 
> Can you try with the OpenCL Intercept Layer DLL in the same directory as cliloader?
> 
> If this still does not work, can you please include the output with the `--debug` command line option? It will look something like this:
> 
> ```
> >\git\CLIntercept\Builds\x64\RelWithDebInfo\cliloader.exe --debug julia.exe
> [cliloader debug] setting environment variable CLI_ReportToStderr to 1
> [cliloader debug] position after parsing arg '\git\CLIntercept\Builds\x64\RelWithDebInfo\cliloader.exe' is 56
> [cliloader debug] position after parsing arg '--debug' is 65
> [cliloader debug] position after skipping non-whitespace characters is 65
> [cliloader debug] position after skipping whitespace characters is 66
> [cliloader debug] pProcessName is non-NULL: \cliloader.exe
> [cliloader debug] process directory is: D:\git\CLIntercept\Builds\x64\RelWithDebInfo
> [cliloader debug] CLI_SuppressLogging is currently:
> [cliloader debug] path to OpenCL.dll is: D:\git\CLIntercept\Builds\x64\RelWithDebInfo\opencl.dll
> [cliloader debug] loaded DLL
> ```
> 
> Thanks!

Thanks Ashbaugh! It works now! I used `--target install` to build the library. It indeed different with linux. I will close the issue now.
