### ISSUE TITLE
"too long" instead of event_list in clWaitForEvents

### ISSUE THREAD

**Issue by mwalkowi** [intel/opencl-intercept-layer#92]
## Observed Behavior

```
>>>> TID = 4596 clRetainEvent: [ ref count = 1 ] event = 00000000052AA270
<<<< TID = 4596 clRetainEvent: [ ref count = 2 ]
>>>> TID = 4596 clWaitForEvents: too long
<<<< TID = 4596 clWaitForEvents
>>>> TID = 4596 clReleaseEvent: [ ref count = 2 ] event = 00000000052AAE10
<<<< TID = 4596 clReleaseEvent: [ ref count = 1 ]
```

## Desired Behavior

```
>>>> TID = 4596 clRetainEvent: [ ref count = 1 ] event = 00000000052AA270
<<<< TID = 4596 clRetainEvent: [ ref count = 2 ]
>>>> TID = 4596 clWaitForEvents: event_list = (size = 500 <# or more #>) [ 00000000052AA270, 00000000052AA271, ... ]
<<<< TID = 4596 clWaitForEvents
>>>> TID = 4596 clReleaseEvent: [ ref count = 2 ] event = 00000000052AAE10
<<<< TID = 4596 clReleaseEvent: [ ref count = 1 ]
```

## Steps to Reproduce

To repro the issue, please use GITS stream from `mwalkowi\clIntercept-repros` (from Intel internal IGK share - please contact me for details). I have put there also full log and registry keys I have used (.reg file).

To run it you need to gitsPlayer from `mwalkowi\gits` (from share) - I am using version 186 combined with fix from `mwalkowi\gits\hotfix-gits-169` (to support device only staff correctly).

The stream was run on SKL GT4e. clIntercept was built today:
```
CLIntercept (64-bit) is loading...
CLintercept file location: C:\Windows\SYSTEM32\OpenCL.dll
CLIntercept URL: https://github.com/intel/opencl-intercept-layer
CLIntercept git description: v2.2-55-g6a016b9
CLIntercept git refspec: refs/heads/embargo
CLInterecpt git hash: 6a016b9c6a7d13e14e8b620dbf3cc99f5ee311bb
CLIntercept environment variable prefix: CLI_
CLIntercept registry key: SOFTWARE\INTEL\IGFX\CLINTERCEPT
```.

**Comment by mwalkowi** [comment]
Sorry, I have used older version, but on new one it is still there:
```
>>>> TID = 3916 clRetainEvent: [ ref count = 2 ] event = 0000000122DD4050
<<<< TID = 3916 clRetainEvent: [ ref count = 3 ] -> CL_SUCCESS
>>>> TID = 3916 clWaitForEvents: too long
<<<< TID = 3916 clWaitForEvents -> CL_SUCCESS
>>>> TID = 3916 clReleaseEvent: [ ref count = 3 ] event = 0000000122DCCE00
<<<< TID = 3916 clReleaseEvent: [ ref count = 2 ] -> CL_SUCCESS
```

**Comment by bashbaug** [comment]
Hi, and thank you for your report!

This is occurring because the call logging strings are currently being constructed from an allocation on the stack.  CLIntercept used to allocate on the heap, which supported much longer strings, but this was quite a bit slower and overkill for most call logging usages - though not all, obviously!

Couple of options:
* The max string size before it is considered "too long" is currently 1024 characters.  We could increase this, which may solve this problem, but a "too long" error could still occur.
* We could switch back to heap allocations.
* We could add an option to switch to heap allocations, but continue to use stack allocations by default.
* We could allocate a fairly large buffer from the heap during initialization and use + recycle it vs. allocating off of the stack.  We could even grow this allocation if we wanted to, but this might be unnecessary since the buffer could be much larger than the current 1024 characters.

I think I'll try the last option and see how well it works.

**Comment by bashbaug** [comment]
Minor note: It's still technically possible to see the "too long" message after #94, but given that the string buffer is now 16KB vs. 1KB it should not be seen in most typical (and even atypical) use-cases.
